# Generated by Django 3.0.5 on 2020-04-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Отображаемое имя')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Фамилия')),
                ('reg_time', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('visited_time', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего посещения')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='Аватарка')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('info', models.TextField(verbose_name='Информация')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('change_time', models.DateTimeField(verbose_name='Время изменения')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.Author', verbose_name='Автор')),
                ('votes', models.ManyToManyField(related_name='comment_vote', to='question.Author', verbose_name='Голоса')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('number_questions', models.PositiveIntegerField(default=0, verbose_name='количество вопросов')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Синоним',
                'verbose_name_plural': 'Синонимы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('change_time', models.DateTimeField(verbose_name='Время изменения')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('header', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('action_time', models.DateTimeField(verbose_name='время последнего действия')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('url', models.SlugField(max_length=150, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.Author', verbose_name='Автор')),
                ('comments', models.ManyToManyField(related_name='question_comment', to='question.Comment', verbose_name='комментарии')),
                ('tags', models.ManyToManyField(related_name='question_tags', to='question.Tag', verbose_name='Тэги')),
                ('votes', models.ManyToManyField(related_name='question_vote', to='question.Author', verbose_name='Голоса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('change_time', models.DateTimeField(verbose_name='Время изменения')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('correct_answer', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.Author', verbose_name='Автор')),
                ('comments', models.ManyToManyField(related_name='answer_comment', to='question.Comment', verbose_name='комментарии')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='Вопрос')),
                ('votes', models.ManyToManyField(related_name='answer_vote', to='question.Author', verbose_name='Голоса')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
