# Generated by Django 3.0.5 on 2020-04-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200416_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='change_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='change_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='question',
            name='action_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время последнего действия'),
        ),
        migrations.AlterField(
            model_name='question',
            name='change_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
