# Generated by Django 3.0.5 on 2020-04-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200416_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='info',
            field=models.TextField(default=django.db.models.deletion.SET_NULL, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default=django.db.models.deletion.SET_NULL, max_length=100, null=True, verbose_name='Имя Фамилия'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(default=django.db.models.deletion.SET_NULL, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(default=django.db.models.deletion.SET_NULL, null=True, verbose_name='Описание'),
        ),
    ]
