# Generated by Django 3.0.5 on 2020-04-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20200416_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='info',
            field=models.TextField(default='', verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя Фамилия'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
