# Generated by Django 3.0.5 on 2020-04-17 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20200416_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='question',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Answer', verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='answer_vote', to='question.Author', verbose_name='Голоса'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='author',
            name='info',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nickname',
            field=models.CharField(max_length=100, unique=True, verbose_name='Отображаемое имя'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='comment_vote', to='question.Author', verbose_name='Голоса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='question_vote', to='question.Author', verbose_name='Голоса'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='number_questions',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='количество вопросов'),
        ),
    ]
