# Generated by Django 3.0.5 on 2020-04-18 18:01

from django.db import migrations


def merge_relations(apps, schema_editor):
    comments = apps.get_model('question', 'Comment')
    for comment in comments.objects.all():
        comment.content_object = comment.answer if comment.answer else comment.question
        comment.content_type = ContentType.objects.get_for_model(comment.content_object)
        comment.object_id = comment.content_object.id

class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20200417_0933'),
    ]

    operations = [
        migrations.RunPython(merge_relations)
    ]
